using Sales.DTOs;
using Sales.Models;
using System.Threading.Tasks;

namespace Sales.Queries;

/// <summary>
/// Class CreateSalesManQuery creates a <see cref="SalesMan"/> which is saved in the Database
/// </summary>
public class CreateSalesManQuery : IQuery<SalesMan> {
    private readonly SalesDbContextFactory contextFactory;

    public CreateSalesManQuery(SalesDbContextFactory contextFactory) {
        this.contextFactory = contextFactory;
    }

    public async Task Execute(SalesMan salesMan) {
        using SalesDbContext context = this.contextFactory.Create();

        SalesManDto salesManDto = new() {
            SalesManId = salesMan.SalesManId,
            Firstname = salesMan.Firstname,
            Lastname = salesMan.Lastname,
            EmployeeStat = (int)salesMan.EmployeeStat
        };

        context.SalesMen.Add(salesManDto);
        await context.SaveChangesAsync();

        // Autogenerated id is set after saving changes
        salesMan.SalesManId = salesManDto.SalesManId;
    }
}
