using Sales.DTOs;
using Sales.Models;
using System.Threading.Tasks;

namespace Sales.Queries;

/// <summary>
/// Class CreateProductLineQuery creates a <see cref="ProductLine"/> which is saved in the Database
/// </summary>
public class CreateProductLineQuery : IQuery<ProductLine> {
    private readonly SalesDbContextFactory contextFactory;

    public CreateProductLineQuery(SalesDbContextFactory contextFactory) {
        this.contextFactory = contextFactory;
    }

    public async Task Execute(ProductLine productLine) {
        using SalesDbContext context = this.contextFactory.Create();

        ProductLineDto productLineDto = new() {
            ProdLineId = productLine.ProdLineId,
            ProductId = productLine.ProductId,
            SalesManId = productLine.SalesManId,
            SalesDate = productLine.SalesDate,
            Price = productLine.Price,
            Amount = productLine.Amount,
            TotalPrice = productLine.TotalPrice,
        };

        context.ProductLines.Add(productLineDto);
        await context.SaveChangesAsync();

        // Autogenerated id is set after saving changes
        productLine.ProdLineId = productLineDto.ProdLineId;
    }
}
